[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "palliative-care-esas-symptom-engine"
version = "2.0.0"
description = "ESAS-Palliative: Edmonton Symptom Assessment System & Opioid Distress"
readme = "README.md"
authors = [{ name = "Dr. Abu Suraih Sakhri", email = "abusuraih@example.com" }]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Security/Cryptography",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
palliative-care-esas-symptom-engine = "esas_palliative.cli:main"

[project.urls]
Homepage = "https://github.com/abusuraihsakhri/palliative-care-esas-symptom-engine"
Repository = "https://github.com/abusuraihsakhri/palliative-care-esas-symptom-engine.git"
